name: CI/CD Pipeline - Analytics Service

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      skip_tests:
        description: 'Skip tests during deployment'
        required: false
        default: 'false'

env:
  DOCKER_IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/analytics-service
  NAMESPACE: analytics

jobs:
  ci-build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        if: ${{ github.event.inputs.skip_tests != 'true' }}
        run: |
          echo "No tests defined yet - add pytest/unittest here"

      # --- Docker Setup ---
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and Push Docker image
        id: docker_build
        run: |
          IMAGE_TAG=${{ github.sha }}
          docker build -t ${{ env.DOCKER_IMAGE_NAME }}:$IMAGE_TAG .
          docker push ${{ env.DOCKER_IMAGE_NAME }}:$IMAGE_TAG
          echo "image-tag=$IMAGE_TAG" >> $GITHUB_OUTPUT

      # --- Update Kubernetes Manifest ---
      - name: Update Deployment Manifest
        run: |
          sed -i "s|image: .*/analytics-service:.*|image: ${{ env.DOCKER_IMAGE_NAME }}:${{ steps.docker_build.outputs.image-tag }}|" k8s-manifest/analytics-service.yaml
