name: CI/CD Pipeline - Analytics Service

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      skip_tests:
        description: 'Skip tests during deployment'
        required: false
        default: 'false'

jobs:
  # --- 1. CI Build & Test ---
  ci-build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        if: ${{ github.event.inputs.skip_tests != 'true' }}
        run: |
          echo "No tests defined yet - add pytest/unittest here"
          # Example: pytest --maxfail=1 --disable-warnings -q

  # --- 2. CD Deploy ---
  cd-deploy:
    runs-on: self-hosted
    needs: ci-build-test
    if: always() && (needs.ci-build-test.result == 'success' || github.event.inputs.skip_tests == 'true')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and Push Docker image
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/analytics-service
          IMAGE_TAG=${{ github.sha }}
          echo "Building image $IMAGE_NAME:$IMAGE_TAG"
          docker build -t $IMAGE_NAME:$IMAGE_TAG .
          docker push $IMAGE_NAME:$IMAGE_TAG
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Update Deployment Manifest
        run: |
          sed -i "s|image: .*/analytics-service:.*|image: $IMAGE_NAME:$IMAGE_TAG|" k8s-manifest/analytics-service.yaml

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f k8s-manifest/
